#!/bin/bash

# W3mimgdisplay path (on some systems, this can be different
w3mimgdisplay=/usr/libexec/w3m/w3mimgdisplay

# Run as a display server
if [ "$1" = "-server" ] ; then
	test ! -f ~/.w3m/w3mimgcode && touch ~/.w3m/w3mimgcode
	while true; do
		# Kill if w3m stops
		# TODO: investigate why `if pidof w3m` works in shell but not inside this script
		if [ -z "$(pidof w3m)" ] ; then
			exit
		fi
		# Feed the saved input to w3mimgdisplay
		$w3mimgdisplay < ~/.w3m/w3mimgcode > /dev/null
		sleep 0.1
	done
# Initialize and give w3m the output it needs
elif [ "$1" = "-test" ] ; then
	# Outputs the size of the current terminal
	if $w3mimgdisplay -test ; then
    # start the wrapper in the background to continuesly display images when needed
    $0 -server &
  else
    # exit with non zero status
    exit 1
  fi
else
	# Gather input from w3m without blocking.
	while true; do
		# Read with timeout
		IFS= read -r -t 0.1 -s holder && LINE="$holder"
		INPUT_BUFFER="${INPUT}\n${LINE}"
		INPUT="$INPUT_BUFFER"
		if [ "$LINE" = "4;" ] ; then
			break
		fi
	done
	# Save the input to be executed by `$0 -server`
	echo -e "$INPUT" > ~/.w3m/w3mimgcode 
fi

